"""
SEC-301: SQL Safety Utilities
Validation for SQL identifiers and parameterized query helpers.
Prevents SQL injection in DDL statements and dynamic queries.
"""
import re
import logging

from utils.i18n import http_error

logger = logging.getLogger("aman.sql_safety")

# Pattern: alphanumeric + underscore only, starting with letter or underscore
_IDENTIFIER_PATTERN = re.compile(r'^[a-zA-Z_][a-zA-Z0-9_]*$')
# Pattern for database/user names generated by AMAN (e.g., aman_abc123, company_abc123)
_AMAN_IDENTIFIER_PATTERN = re.compile(r'^[a-z0-9_]+$')


def validate_sql_identifier(name: str, label: str = "identifier") -> str:
    """
    Validate that a string is a safe SQL identifier.
    Raises ValueError if the name contains dangerous characters.
    
    Args:
        name: The identifier to validate
        label: Human-readable label for error messages
    
    Returns:
        The validated name (unchanged)
    """
    if not name or not isinstance(name, str):
        raise ValueError(f"Invalid {label}: empty or non-string")
    
    if len(name) > 128:
        raise ValueError(f"Invalid {label}: too long (max 128 chars)")
    
    if not _IDENTIFIER_PATTERN.match(name):
        raise ValueError(
            f"Invalid {label} '{name}': must contain only letters, numbers, and underscores, "
            f"starting with a letter or underscore"
        )
    
    # Block SQL keywords as identifiers
    SQL_KEYWORDS = {
        'select', 'insert', 'update', 'delete', 'drop', 'create', 'alter',
        'truncate', 'grant', 'revoke', 'union', 'where', 'from', 'table',
        'database', 'user', 'password', 'exec', 'execute'
    }
    if name.lower() in SQL_KEYWORDS:
        raise ValueError(f"Invalid {label}: '{name}' is a reserved SQL keyword")
    
    return name


def validate_aman_identifier(name: str, label: str = "identifier") -> str:
    """
    Validate AMAN-generated identifiers (database names, user names).
    These follow the pattern: aman_<hex> or company_<hex>
    
    Args:
        name: The identifier to validate
        label: Human-readable label for error messages
    
    Returns:
        The validated name (unchanged)
    """
    if not name or not isinstance(name, str):
        raise ValueError(f"Invalid {label}: empty or non-string")
    
    if len(name) > 128:
        raise ValueError(f"Invalid {label}: too long (max 128 chars)")
    
    if not _AMAN_IDENTIFIER_PATTERN.match(name):
        raise ValueError(
            f"Invalid {label} '{name}': must contain only lowercase letters, numbers, and underscores"
        )
    
    return name


def validate_password_strength(password: str, request=None) -> None:
    """
    SEC-302: Validate password meets security requirements.
    Raises HTTPException if password is too weak.
    
    Requirements:
    - Minimum 10 characters
    - At least one uppercase letter  
    - At least one lowercase letter
    - At least one digit
    - At least one special character
    """
    from fastapi import HTTPException
    
    if len(password) < 10:
        raise HTTPException(**http_error(400, "password_min_length", request))
    if not re.search(r'[A-Z]', password):
        raise HTTPException(**http_error(400, "password_requires_uppercase", request))
    if not re.search(r'[a-z]', password):
        raise HTTPException(**http_error(400, "password_requires_lowercase", request))
    if not re.search(r'[0-9]', password):
        raise HTTPException(**http_error(400, "password_requires_digit", request))
    if not re.search(r'[^A-Za-z0-9]', password):
        raise HTTPException(**http_error(400, "password_requires_special", request))


# File upload security constants
MAX_DOCUMENT_SIZE = 50 * 1024 * 1024  # 50 MB
MAX_IMPORT_FILE_SIZE = 10 * 1024 * 1024  # 10 MB
MAX_LOGO_SIZE = 5 * 1024 * 1024  # 5 MB
MAX_FILENAME_BYTES = 255

BLOCKED_FILE_EXTENSIONS = {
    '.exe', '.bat', '.cmd', '.sh', '.php', '.jsp', '.py', '.rb',
    '.pl', '.cgi', '.com', '.scr', '.pif', '.vbs', '.js', '.ws',
    '.wsf', '.msi', '.dll', '.sys', '.drv', '.ps1', '.psm1'
}

ALLOWED_IMAGE_EXTENSIONS = {'.jpg', '.jpeg', '.png', '.gif', '.svg', '.webp', '.bmp'}
ALLOWED_IMPORT_EXTENSIONS = {'.csv', '.xlsx', '.xls'}
ALLOWED_DOCUMENT_EXTENSIONS = {
    '.pdf', '.doc', '.docx', '.xls', '.xlsx', '.ppt', '.pptx',
    '.txt', '.csv', '.jpg', '.jpeg', '.png', '.gif', '.svg',
    '.zip', '.rar', '.7z'
}

_ALLOWED_MIME_BY_EXT = {
    ".pdf": {"application/pdf"},
    ".jpg": {"image/jpeg"},
    ".jpeg": {"image/jpeg"},
    ".png": {"image/png"},
    ".gif": {"image/gif"},
    ".webp": {"image/webp"},
    ".bmp": {"image/bmp", "image/x-ms-bmp"},
    ".svg": {"image/svg+xml", "text/xml", "application/xml"},
    ".csv": {"text/csv", "application/csv", "application/vnd.ms-excel", "text/plain"},
    ".txt": {"text/plain"},
    ".zip": {"application/zip", "application/x-zip-compressed", "application/octet-stream"},
    ".rar": {"application/vnd.rar", "application/x-rar-compressed", "application/octet-stream"},
    ".7z": {"application/x-7z-compressed", "application/octet-stream"},
    ".doc": {"application/msword", "application/octet-stream"},
    ".xls": {"application/vnd.ms-excel", "application/octet-stream"},
    ".ppt": {"application/vnd.ms-powerpoint", "application/octet-stream"},
    ".docx": {"application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/zip", "application/octet-stream"},
    ".xlsx": {"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/zip", "application/octet-stream"},
    ".pptx": {"application/vnd.openxmlformats-officedocument.presentationml.presentation", "application/zip", "application/octet-stream"},
}

_SIGNATURES_BY_EXT = {
    ".pdf": [b"%PDF-"],
    ".png": [b"\x89PNG\r\n\x1a\n"],
    ".jpg": [b"\xff\xd8\xff"],
    ".jpeg": [b"\xff\xd8\xff"],
    ".gif": [b"GIF87a", b"GIF89a"],
    ".bmp": [b"BM"],
    ".zip": [b"PK\x03\x04", b"PK\x05\x06", b"PK\x07\x08"],
    ".docx": [b"PK\x03\x04", b"PK\x05\x06", b"PK\x07\x08"],
    ".xlsx": [b"PK\x03\x04", b"PK\x05\x06", b"PK\x07\x08"],
    ".pptx": [b"PK\x03\x04", b"PK\x05\x06", b"PK\x07\x08"],
    ".rar": [b"Rar!\x1a\x07\x00", b"Rar!\x1a\x07\x01\x00"],
    ".7z": [b"\x37\x7a\xbc\xaf\x27\x1c"],
    ".doc": [b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1"],
    ".xls": [b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1"],
    ".ppt": [b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1"],
}


def validate_file_size(content: bytes, max_size: int, label: str = "الملف", request=None) -> None:
    """Validate uploaded file doesn't exceed maximum size"""
    from fastapi import HTTPException
    if len(content) > max_size:
        max_mb = max_size / (1024 * 1024)
        raise HTTPException(**http_error(413, "file_size_exceeded", request, max_mb=f"{max_mb:.0f}"))


def validate_file_extension(filename: str, allowed: set = None, label: str = "الملف", request=None) -> str:
    """
    Validate file extension is safe.
    
    Args:
        filename: The original filename
        allowed: Set of allowed extensions (if None, just blocks dangerous ones)
        label: Human-readable label for error messages
    
    Returns:
        The file extension (lowercase)
    """
    import os
    from fastapi import HTTPException
    
    if not filename:
        raise HTTPException(**http_error(400, "file_name_required", request))

    safe_name = os.path.basename(filename)
    if len(safe_name.encode("utf-8")) > MAX_FILENAME_BYTES:
        raise HTTPException(**http_error(400, "file_name_too_long", request, max=MAX_FILENAME_BYTES))
    
    ext = os.path.splitext(filename)[1].lower()

    # T10.2 #166 — Double-extension protection. ``os.path.splitext`` only
    # returns the LAST extension, so ``shell.php.pdf`` would slip past as
    # ``.pdf``. Apache/nginx mishandling can still execute the inner
    # ``.php``. Defense: scan ALL dot-segments of the filename for any
    # blocked extension.
    base = os.path.basename(filename).lower()
    parts = base.split(".")
    if len(parts) > 2:  # at least one inner segment besides name + final ext
        for seg in parts[1:-1]:
            if f".{seg}" in BLOCKED_FILE_EXTENSIONS:
                raise HTTPException(
                    400,
                    f"اسم {label} يحتوي امتدادًا داخليًا غير مسموح (.{seg})",
                )

    # Always block dangerous extensions
    if ext in BLOCKED_FILE_EXTENSIONS:
        raise HTTPException(**http_error(400, "file_type_not_allowed", request, ext=ext))
    
    # If allowed set provided, check against it
    if allowed and ext not in allowed:
        raise HTTPException(**http_error(400, "file_type_not_supported", request, types=", ".join(sorted(allowed))))
    
    return ext


def validate_file_path_safety(file_path: str, base_dir: str) -> bool:
    """
    Validate that a file path is within the expected base directory.
    Prevents path traversal attacks.
    
    Returns True if safe, False if potentially malicious.
    """
    import os
    abs_path = os.path.abspath(file_path)
    abs_base = os.path.abspath(base_dir)
    return abs_path.startswith(abs_base + os.sep) or abs_path == abs_base


def validate_file_mime_and_signature(
    filename: str,
    content_type: str,
    content: bytes,
    label: str = "الملف",
    request=None,
) -> str:
    """
    Validate uploaded file MIME type and binary signature (magic bytes).
    Returns validated extension.
    """
    from fastapi import HTTPException
    import os

    if not content:
        raise HTTPException(**http_error(400, "file_empty", request))

    ext = os.path.splitext(filename or "")[1].lower()
    if not ext:
        raise HTTPException(**http_error(400, "file_extension_unclear", request))

    # MIME validation (if provided by client/proxy).
    normalized_ct = (content_type or "").split(";")[0].strip().lower()
    allowed_mimes = _ALLOWED_MIME_BY_EXT.get(ext)
    if normalized_ct and allowed_mimes and normalized_ct not in allowed_mimes:
        raise HTTPException(**http_error(400, "file_signature_mismatch", request, ext=ext))

    # Signature validation for binary formats we can confidently detect.
    if ext == ".webp":
        if not (len(content) >= 12 and content.startswith(b"RIFF") and content[8:12] == b"WEBP"):
            raise HTTPException(**http_error(400, "file_invalid_webp_signature", request))
        return ext

    signatures = _SIGNATURES_BY_EXT.get(ext, [])
    if signatures and not any(content.startswith(sig) for sig in signatures):
        raise HTTPException(**http_error(400, "file_signature_mismatch", request, ext=ext))

    # Text formats: block NUL-bytes to reduce disguised binaries.
    if ext in {".txt", ".csv", ".svg"} and b"\x00" in content:
        raise HTTPException(**http_error(400, "file_invalid_text_content", request))

    return ext
