"""Central ORM model exports.

Developer guidance:
- Prefer domain-first discovery under backend.models.domains for new work.
- Phase files remain as compatibility/history from incremental rollout.
- Keep this module as the stable export surface for legacy imports.
"""

from .base import ModelBase
from .domain_models.core_business import (
    CompanySetting,
    Invoice,
    InvoiceLine,
    Party,
    PartyGroup,
    TreasuryAccount,
    UserBranch,
    Warehouse,
)
from .domain_models.core_accounting import Account, Branch, CompanyUser, JournalEntry, JournalLine
from .domain_models.hr_core_payroll import (
    Attendance,
    Department,
    Employee,
    EmployeeLoan,
    EmployeePosition,
    EmployeeSalaryComponent,
    LeaveRequest,
    PayrollEntry,
    PayrollPeriod,
    SalaryComponent,
    SalaryStructure,
)
from .domain_models.inventory_core import (
    Inventory,
    InventoryTransaction,
    Product,
    ProductCategory,
    ProductUnit,
    StockAdjustment,
)
from .domain_models.procurement_orders import PurchaseOrder, PurchaseOrderLine, BlanketPurchaseOrder, BlanketPOReleaseOrder
from .domain_models.finance_treasury_tax import (
    BankReconciliation,
    BankStatementLine,
    BranchTaxSetting,
    CompanyTaxSetting,
    TaxGroup,
    TaxPayment,
    TaxRate,
    TaxRegime,
    TaxReturn,
    TreasuryTransaction,
)
from .domain_models.projects_core import (
    Project,
    ProjectBudget,
    ProjectChangeOrder,
    ProjectDocument,
    ProjectExpense,
    ProjectRevenue,
    ProjectTask,
)
from .domain_models.operations_financial_support import (
    CheckPayable,
    CheckReceivable,
    Document,
    DocumentVersion,
    Expense,
    NotePayable,
    NoteReceivable,
    ServiceRequest,
    ServiceRequestCost,
    SupportTicket,
    TicketComment,
)
from .domain_models.security_approvals import ApprovalAction, ApprovalRequest, ApprovalWorkflow
from .domain_models.assets_core import Asset, AssetCategory, AssetTransfer
from .domain_models.finance_budgets import Budget, BudgetItem, BudgetLine
from .domain_models.finance_costing import (
    CostCenter,
    CostCenterBudget,
    CostingPolicy,
    CostingPolicyDetail,
    CostingPolicyHistory,
    InventoryCostSnapshot,
)
from .domain_models.assets_advanced import (
    AssetDepreciationSchedule,
    AssetDisposal,
    AssetImpairment,
    AssetInsurance,
    AssetMaintenance,
    AssetRevaluation,
)
from .domain_models.finance_currency_bank import BankImportBatch, BankImportLine, Currency, ExchangeRate
from .domain_models.finance_fiscal_zakat import FiscalPeriodLock, FiscalYear, ZakatCalculation
from .domain_models.projects_contracts_expenses import Contract, ContractItem, ExpensePolicy
from .domain_models.projects_crm_advanced import (
    Campaign,
    CampaignLeadAttribution,
    CampaignRecipient,
    CrmCustomerSegment,
    CrmCustomerSegmentMember,
    CrmLeadScore,
    CrmLeadScoringRule,
    CrmSalesForecast,
)
from .domain_models.security_admin_reporting import ApiKey, AuditLog, BackupHistory, CustomReport, EmailTemplate
from .domain_models.inventory_advanced import (
    BatchSerialMovement,
    BinInventory,
    BinLocation,
    CycleCount,
    CycleCountItem,
)
from .domain_models.inventory_advanced import (
    ProductAttribute,
    ProductAttributeValue,
    ProductKit,
    ProductVariant,
    ProductVariantAttribute,
)
from .domain_models.inventory_advanced import (
    ProductBatch,
    ProductKitItem,
    ProductSerial,
    QualityInspection,
    QualityInspectionCriteria,
)
from .domain_models.sales_customers_delivery import (
    Customer,
    CustomerBankAccount,
    CustomerContact,
    CustomerPriceList,
    CustomerPriceListItem,
)
from .domain_models.sales_customers_delivery import (
    CustomerBalance,
    CustomerReceipt,
    CustomerTransaction,
    DeliveryOrder,
    DeliveryOrderLine,
)
from .domain_models.hr_compliance_recruitment import (
    EmployeeCustody,
    EmployeeDocument,
    EmployeeViolation,
    JobApplication,
    JobOpening,
)
from .domain_models.operations_attachments_commissions import Attachment, CommissionRule
from .domain_models.manufacturing_bom_capacity import BillOfMaterial, BomOutput
from .domain_models.security_admin_reporting import CheckStatusLog
from .domain_models.projects_crm_contract_extensions import CrmContact, ContractAmendment, CrmKnowledgeBase, CustomerGroup
from .domain_models.finance_currency_transactions import CurrencyTransaction
from .domain_models.security_admin_reporting import DocumentTemplate, DocumentType, FinancialReport
from .domain_models.manufacturing_bom_capacity import BomComponent, CapacityPlan
from .domain_models.shared_dashboard_fiscal_intercompany import (
    AnalyticsDashboard,  # noqa: F401
    AnalyticsDashboardWidget,  # noqa: F401
    DashboardLayout,
    FiscalPeriod,
    GosiSetting,
    IntercompanyTransaction,
    LandedCostAllocation,
)
from .domain_models.finance_cashflow import (
    PartyTransaction,
    Payment,
    PaymentAllocation,
    PaymentVoucher,
    RecurringJournalLine,
    RecurringJournalTemplate,
)
from .domain_models.finance_forecast import CashFlowForecast, CashFlowForecastLine
from .domain_models.finance_recognition_tax import RevenueRecognitionSchedule, TaxCalendar, WhtRate, WhtTransaction
from .domain_models.hr_training import TrainingParticipant, TrainingProgram
from .domain_models.hr_workforce import LeaveCarryover, OvertimeRequest, PerformanceReview, ReviewCycle, PerformanceGoal
from .domain_models.inventory_transfers import StockShipment, StockShipmentItem, StockTransferLog
from .domain_models.manufacturing_execution import (
    ManufacturingEquipment,
    ManufacturingOperation,
    ManufacturingRoute,
    MfgQcCheck,
    MrpItem,
    MrpPlan,
    ProductionOrder,
    ProductionOrderOperation,
    ShopFloorLog,
)
from .domain_models.manufacturing_resources import WorkCenter
from .domain_models.operations_support import LeaseContract, MaintenanceLog, MarketingCampaign
from .domain_models.procurement_costs import (
    LandedCost,
    LandedCostItem,
    PendingPayable,
    PurchaseAgreement,
    PurchaseAgreementLine,
)
from .domain_models.procurement_suppliers import (
    Supplier,
    SupplierBalance,
    SupplierBankAccount,
    SupplierContact,
    SupplierGroup,
    SupplierPayment,
    SupplierRating,
    SupplierTransaction,
)
from .domain_models.projects_dependencies import TaskDependency
from .domain_models.projects_execution import OpportunityActivity, ProjectRisk, ProjectTimesheet
from .domain_models.sales_pos import (
    PendingReceivable,
    PosKitchenOrder,
    PosLoyaltyPoint,
    PosLoyaltyProgram,
    PosLoyaltyTransaction,
    PosOrder,
    PosOrderLine,
    PosOrderPayment,
    PosPayment,
    PosPromotion,
    PosReturn,
    PosReturnItem,
    PosSession,
    PosTable,
    PosTableOrder,
    Receipt,
)
from .domain_models.sales_rfq import (
    RequestForQuotation,
    RfqLine,
    RfqResponse,
    SalesCommission,
    SalesOpportunity,
    SalesOrder,
    SalesOrderLine,
    SalesQuotation,
    SalesQuotationLine,
    SalesReturn,
    SalesReturnLine,
    SalesTarget,
)
from .domain_models.cpq import (
    ProductConfiguration,
    ConfigOptionGroup,
    ConfigOption,
    ConfigValidationRule,
    CpqPricingRule,
    CpqQuote,
    CpqQuoteLine,
)
from .domain_models.security_comms import LoginAttempt, Message, Notification, PasswordHistory, PrintTemplate, ReportTemplate
from .domain_models.security_reporting import (
    Role,
    ScheduledReport,
    SecurityEvent,
    SharedReport,
    User2FASetting,
    UserSession,
    WebhookLog,
    Webhook,
)
from .domain_models.intercompany import EntityGroup, IntercompanyTransactionV2, IntercompanyAccountMapping
from .domain_models.inventory_costing import CostLayer, CostLayerConsumption
from .domain_models.matching import MatchTolerance, ThreeWayMatch, ThreeWayMatchLine
from .domain_models.self_service import SelfServiceRequest
from .domain_models.sso import SsoConfiguration, SsoGroupRoleMapping, SsoFallbackAdmin
from .domain_models.mobile_sync import SyncQueue  # noqa: F401
from .domain_models.finance_subscriptions import SubscriptionPlan, SubscriptionEnrollment, SubscriptionInvoice
from .domain_models.demand_forecast import DemandForecast, DemandForecastPeriod


target_metadata = ModelBase.metadata
MODELED_TABLES = set(target_metadata.tables.keys())

__all__ = [
    "ModelBase",
    "UserBranch",
    "PartyGroup",
    "Party",
    "TreasuryAccount",
    "Warehouse",
    "Invoice",
    "InvoiceLine",
    "CompanySetting",
    "CompanyUser",
    "Branch",
    "Account",
    "JournalEntry",
    "JournalLine",
    "ProductCategory",
    "ProductUnit",
    "Product",
    "Inventory",
    "InventoryTransaction",
    "StockAdjustment",
    "PurchaseOrder",
    "PurchaseOrderLine",
    "BlanketPurchaseOrder",
    "BlanketPOReleaseOrder",
    "PayrollPeriod",
    "Department",
    "EmployeePosition",
    "Employee",
    "Attendance",
    "EmployeeLoan",
    "LeaveRequest",
    "SalaryStructure",
    "SalaryComponent",
    "EmployeeSalaryComponent",
    "PayrollEntry",
    "TreasuryTransaction",
    "BankReconciliation",
    "BankStatementLine",
    "TaxRate",
    "TaxGroup",
    "TaxReturn",
    "TaxPayment",
    "TaxRegime",
    "BranchTaxSetting",
    "CompanyTaxSetting",
    "Project",
    "ProjectTask",
    "ProjectBudget",
    "ProjectExpense",
    "ProjectRevenue",
    "ProjectDocument",
    "ProjectChangeOrder",
    "CheckReceivable",
    "CheckPayable",
    "NoteReceivable",
    "NotePayable",
    "Expense",
    "ServiceRequest",
    "ServiceRequestCost",
    "Document",
    "DocumentVersion",
    "SupportTicket",
    "TicketComment",
    "ApprovalWorkflow",
    "ApprovalRequest",
    "ApprovalAction",
    "AssetCategory",
    "Asset",
    "AssetTransfer",
    "Budget",
    "BudgetItem",
    "BudgetLine",
    "CostCenter",
    "CostCenterBudget",
    "CostingPolicy",
    "CostingPolicyDetail",
    "CostingPolicyHistory",
    "InventoryCostSnapshot",
    "AssetDepreciationSchedule",
    "AssetDisposal",
    "AssetRevaluation",
    "AssetInsurance",
    "AssetMaintenance",
    "AssetImpairment",
    "Currency",
    "ExchangeRate",
    "BankImportBatch",
    "BankImportLine",
    "FiscalYear",
    "FiscalPeriodLock",
    "ZakatCalculation",
    "Contract",
    "ContractItem",
    "ExpensePolicy",
    "CrmLeadScoringRule",
    "CrmLeadScore",
    "CrmCustomerSegment",
    "CrmCustomerSegmentMember",
    "CrmSalesForecast",
    "Campaign",
    "CampaignRecipient",
    "CampaignLeadAttribution",
    "ApiKey",
    "AuditLog",
    "BackupHistory",
    "CustomReport",
    "EmailTemplate",
    "BatchSerialMovement",
    "CycleCount",
    "CycleCountItem",
    "BinLocation",
    "BinInventory",
    "ProductAttribute",
    "ProductAttributeValue",
    "ProductVariant",
    "ProductVariantAttribute",
    "ProductKit",
    "ProductBatch",
    "ProductSerial",
    "QualityInspection",
    "QualityInspectionCriteria",
    "ProductKitItem",
    "Customer",
    "CustomerContact",
    "CustomerBankAccount",
    "CustomerPriceList",
    "CustomerPriceListItem",
    "CustomerTransaction",
    "CustomerReceipt",
    "CustomerBalance",
    "DeliveryOrder",
    "DeliveryOrderLine",
    "EmployeeDocument",
    "EmployeeViolation",
    "EmployeeCustody",
    "JobOpening",
    "JobApplication",
    "Attachment",
    "BillOfMaterial",
    "BomOutput",
    "CheckStatusLog",
    "CommissionRule",
    "FinancialReport",
    "DocumentType",
    "DocumentTemplate",
    "CurrencyTransaction",
    "CrmContact",
    "BomComponent",
    "CapacityPlan",
    "CashFlowForecast",
    "CashFlowForecastLine",
    "ContractAmendment",
    "CrmKnowledgeBase",
    "CustomerGroup",
    "DashboardLayout",
    "FiscalPeriod",
    "GosiSetting",
    "IntercompanyTransaction",
    "LandedCostAllocation",
    "LandedCost",
    "LandedCostItem",
    "LeaseContract",
    "LeaveCarryover",
    "LoginAttempt",
    "MaintenanceLog",
    "ManufacturingEquipment",
    "ManufacturingOperation",
    "ManufacturingRoute",
    "MarketingCampaign",
    "Message",
    "MfgQcCheck",
    "MrpItem",
    "MrpPlan",
    "Notification",
    "OpportunityActivity",
    "OvertimeRequest",
    "PartyTransaction",
    "PasswordHistory",
    "PaymentAllocation",
    "PaymentVoucher",
    "Payment",
    "PendingPayable",
    "PendingReceivable",
    "PerformanceGoal",
    "PerformanceReview",
    "PosKitchenOrder",
    "PosLoyaltyPoint",
    "PosLoyaltyProgram",
    "PosLoyaltyTransaction",
    "PosOrderLine",
    "PosOrderPayment",
    "PosOrder",
    "PosPayment",
    "PosPromotion",
    "PosReturnItem",
    "PosReturn",
    "PosSession",
    "PosTableOrder",
    "PosTable",
    "PrintTemplate",
    "ProductionOrderOperation",
    "ProductionOrder",
    "ProjectRisk",
    "ProjectTimesheet",
    "PurchaseAgreementLine",
    "PurchaseAgreement",
    "Receipt",
    "RecurringJournalLine",
    "RecurringJournalTemplate",
    "ReportTemplate",
    "RequestForQuotation",
    "RevenueRecognitionSchedule",
    "ReviewCycle",
    "RfqLine",
    "RfqResponse",
    "Role",
    "SalesCommission",
    "SalesOpportunity",
    "SalesOrderLine",
    "SalesOrder",
    "SalesQuotationLine",
    "SalesQuotation",
    "SalesReturnLine",
    "SalesReturn",
    "SalesTarget",
    "ProductConfiguration",
    "ConfigOptionGroup",
    "ConfigOption",
    "ConfigValidationRule",
    "CpqPricingRule",
    "CpqQuote",
    "CpqQuoteLine",
    "ScheduledReport",
    "SecurityEvent",
    "SharedReport",
    "StockShipmentItem",
    "StockShipment",
    "StockTransferLog",
    "SupplierBalance",
    "SupplierBankAccount",
    "SupplierContact",
    "SupplierGroup",
    "SupplierPayment",
    "SupplierRating",
    "SupplierTransaction",
    "Supplier",
    "TaskDependency",
    "TaxCalendar",
    "TrainingParticipant",
    "TrainingProgram",
    "User2FASetting",
    "UserSession",
    "WebhookLog",
    "Webhook",
    "WhtRate",
    "WhtTransaction",
    "WorkCenter",
    # Phase 2 domain models
    "CostLayer",
    "CostLayerConsumption",
    "EntityGroup",
    "IntercompanyAccountMapping",
    "IntercompanyTransactionV2",
    "MatchTolerance",
    "SelfServiceRequest",
    "SsoConfiguration",
    "SsoFallbackAdmin",
    "SsoGroupRoleMapping",
    "ThreeWayMatch",
    "ThreeWayMatchLine",
    "SubscriptionPlan",
    "SubscriptionEnrollment",
    "SubscriptionInvoice",
    "DemandForecast",
    "DemandForecastPeriod",
    "ShopFloorLog",
    "target_metadata",
    "MODELED_TABLES",
]
